In [58]:
import numpy as np

This is a notebook where I delve deeper into an example used in the book **Reinforcement Learning** by Sutton and Barto, page 71 - 3.7 Value Function

$$ V^{\pi}(s) = \sum_{a} \pi(s,a) \sum_{s^\prime} P_{s{s^\prime}}^{a} 
   (R_{s{s^\prime}}^{a} + \gamma V^{\pi}(s^\prime)) $$
   

- $s$: current state 
- $s^\prime$: next state
- $V^{\pi}(s)$: state-value function for state $s$ following policy $\pi$
- $\pi(s,a)$: policy, the probability of taking action $a$ given state $s$
- $P_{s{s^\prime}}^{a}$: transition probability of ending in $s^\prime$ given taken action $a$ from state $s$
- $R_{s{s^\prime}}^{a}$: reward of ending in $s^\prime$ given taken action $a$ from state $s$

#### Example 3.8: Grid World
[slides page 55](http://slideplayer.com/slide/4789577/)

Let's start by identifying each different state by its cell position, where (x, y) will means the cell is x units away from the left, and y units away from the top. So the top left corner will have the coordinate of (0,0) and the one in the top right will be (4,0), bottom left will be (0, 4) and bottom right will be (4,4). 

Let's start by looking into how to calculate the state - value function for the the state (0,0)

### 1. S=[0,0]

Looking at the bellman equation, we know that we first need to start by looking at the policy and see what are the actions that we can/shall take from state $s$ by following the game policy. The game policy is pretty easy so far, the policy is not to maximize rewards to avoid edge. It is simply a random walk without any particular goal in mind for any state. So at a high level, we know that: 


$$ V^{\pi}(s=[0,0]) = \sum_{a \in (E,S,W,N)} \pi(s=[0,0],a) \sum_{s^\prime} P_{s=[0,0]{s^\prime}}^{a} 
   (R_{s=[0,0]{s^\prime}}^{a} + \gamma V^{\pi}(s^\prime)) $$
 

The good part about this example is that this problem is deterministic. For a starting state, by taken a specific action, you know exactly where you are going next, there is no ramdomness in this problem, even the teleport from A to A' happens with certainty. In another way the transition probability is always 1. Or even further, given state $s$ and action $a$, you know for sure what the next state $s^\prime$ will be so there is only one next step with transition probability of being 1. Now, let's get rid of the summation over the next state space and also the transition probability.  

$$ V^{\pi}(s=[0,0]) = \sum_{a \in (E,S,W,N)} \pi(s=[0,0],a)  
   (R_{s=[0,0]{s^\prime}}^{a} + \gamma V^{\pi}(s^\prime)) $$
 

$$ V^{\pi}(s=[0,0]) = 
\frac{1}{4}(R_{s=[0,0]{s=[1,0]}}^{a=E} + \gamma V^{\pi}(s=[1,0])) + 
\frac{1}{4}(R_{s=[0,0]{s=[0,1]}}^{a=S} + \gamma V^{\pi}(s=[0,1])) + 
\frac{1}{4}(R_{s=[0,0]{s=[0,0]}}^{a=W} + \gamma V^{\pi}(s=[0,0])) + 
\frac{1}{4}(R_{s=[0,0]{s=[0,0]}}^{a=N} + \gamma V^{\pi}(s=[0,0])) $$
 

Now let's look at all the rewards:

- $R_{s=[0,0]{s=[1,0]}}^{a=E} = 0$
- $R_{s=[0,0]{s=[0,1]}}^{a=S} = 0$
- $R_{s=[0,0]{s=[0,0]}}^{a=W} = -1$
- $R_{s=[0,0]{s=[0,0]}}^{a=N} = -1$

Now we can even further drop a few notation to make it look simple

$$ V(s=[0,0]) = 
\frac{1}{4}(0 + \gamma V(s=[1,0])) + 
\frac{1}{4}(0 + \gamma V(s=[0,1])) + 
\frac{1}{4}(-1 + \gamma V(s=[0,0])) + 
\frac{1}{4}(-1 + \gamma V(s=[0,0])) $$
 

$$(4 - 2\gamma)V([0,0]) = \gamma V([1,0]) + \gamma V([0,1]) - 2  $$

For the sake of practicing, let's calculate the state value function for another two cells $A:[1,0]$ and $B^\prime=[3,2]$

### 2. S=[1,0]


$$ V^{\pi}(s=[1,0]) = 
\frac{1}{4}(R_{s=[1,0]{s=[1,4]}}^{a=E} + \gamma V^{\pi}(s=[1,4])) + 
\frac{1}{4}(R_{s=[1,0]{s=[1,4]}}^{a=S} + \gamma V^{\pi}(s=[1,4])) + 
\frac{1}{4}(R_{s=[1,0]{s=[1,4]}}^{a=W} + \gamma V^{\pi}(s=[1,4])) + 
\frac{1}{4}(R_{s=[1,0]{s=[1,4]}}^{a=N} + \gamma V^{\pi}(s=[1,4])) $$
 

Starting from point A, we know that regardless of which action you take, you will always teleport to A' [1,4], and it is a certainty. And the immediate reward is 10 all four directions. We can still following the procedure of starting at the $\pi(s,a)$ and then transition probability, like what we did above, or we can go straight to the next and only state since they are essentially the same in the end:

$$ V(s=[1,0]) = 10 + \gamma V(s=[1,4]) $$
 


### 3. S=[3,2]


$$ V^{\pi}(s=[3,2]) = 
\frac{1}{4}(R_{s=[3,2]{s=[4,2]}}^{a=E} + \gamma V^{\pi}(s=[4,2])) + 
\frac{1}{4}(R_{s=[3,2]{s=[3,3]}}^{a=S} + \gamma V^{\pi}(s=[3,3])) + 
\frac{1}{4}(R_{s=[3,2]{s=[2,2]}}^{a=W} + \gamma V^{\pi}(s=[2,2])) + 
\frac{1}{4}(R_{s=[3,2]{s=[3,1]}}^{a=N} + \gamma V^{\pi}(s=[3,1])) $$
 

Since [3,2] is not next to the edge and there is no special condition, move around will lead to zero reward and each movement is deterministic. 

$$ 4V([3,2]) = 
\gamma V([4,2]) + 
\gamma V([3,3]) + 
\gamma V([2,2]) + 
\gamma V([3,1]) $$
 

### 3. Iterate through all the cells


If we go through the cell one by one, we will have 25 equations and the number of unknowns will also be 25 given $\gamma = 0.9$. Actually, 25 is not the end of the world, why don't we just write down all the equations and see if we can solve it, or if it is even solvable or not (if those equations are not independent, then we will not be able to find a unique solution). Of course, for that many equations, let's simplify the notation even further more to save some real estate on the screen, $V([x,y])$ now will be represented in $V_{xy}$. 

Also, manualy write down everything is a bit tediou, let us write a utility function to auto generate all the 25 functions.

$$ 4V_{xy} =
r_{x+1,y} + V_{x+1,y} + 
r_{x,y+1} + V_{x,y+1} +
r_{x-1,y} + V_{x-1,y} +
r_{x,y-1} + V_{x+1,y-1} $$

We can easily write a logic to determine r because if the subscript of r goes out of bound, like not within the range between 0 and 4. We know it hit the wall and should change the corresponding V to be the starting cell and at the same time, set the reward to be -1. Otherwise, it is 0. In the end, we can override the equation for A,B to account for the teleport situation:

In [57]:
# I am really interested in finding a more neat way of coding this logic
size = 5
for x in range(size):
    for y in range(size):
        equation = """$$4V_{{{0}{1}}}=""".format(x,y)
        step = """\gamma V_{{{x_}{y_}}}+{r}"""
        # build up each step 
        # E: x+1, y
        r = 0
        x_ = x+1
        y_ = y 
        if x_ > size - 1:
            x_ = x
            r = -1
        equation = equation + step.format(**{'r':r, 'x_':x_, 'y_':y_})
        
        # S: x, y+1
        r = 0
        x_ = x
        y_ = y+1 
        if y_ > size - 1:
            y_ = y
            r = -1
        equation = equation + '+' + step.format(**{'r':r, 'x_':x_, 'y_':y_})

        # W: x-1, y
        r = 0
        x_ = x-1
        y_ = y 
        if x_ < 0:
            x_ = x
            r = -1
        equation = equation + '+' + step.format(**{'r':r, 'x_':x_, 'y_':y_})

        # N: x, y-1
        r = 0
        x_ = x
        y_ = y-1 
        if y_ < 0:
            y_ = y
            r = -1
        equation = equation + '+' + step.format(**{'r':r, 'x_':x_, 'y_':y_})
        
        equation += " $$"
        print(equation)

$$4V_{00}=\gamma V_{10}+0+\gamma V_{01}+0+\gamma V_{00}+-1+\gamma V_{00}+-1 $$
$$4V_{01}=\gamma V_{11}+0+\gamma V_{02}+0+\gamma V_{01}+-1+\gamma V_{00}+0 $$
$$4V_{02}=\gamma V_{12}+0+\gamma V_{03}+0+\gamma V_{02}+-1+\gamma V_{01}+0 $$
$$4V_{03}=\gamma V_{13}+0+\gamma V_{04}+0+\gamma V_{03}+-1+\gamma V_{02}+0 $$
$$4V_{04}=\gamma V_{14}+0+\gamma V_{04}+-1+\gamma V_{04}+-1+\gamma V_{03}+0 $$
$$4V_{10}=\gamma V_{20}+0+\gamma V_{11}+0+\gamma V_{00}+0+\gamma V_{10}+-1 $$
$$4V_{11}=\gamma V_{21}+0+\gamma V_{12}+0+\gamma V_{01}+0+\gamma V_{10}+0 $$
$$4V_{12}=\gamma V_{22}+0+\gamma V_{13}+0+\gamma V_{02}+0+\gamma V_{11}+0 $$
$$4V_{13}=\gamma V_{23}+0+\gamma V_{14}+0+\gamma V_{03}+0+\gamma V_{12}+0 $$
$$4V_{14}=\gamma V_{24}+0+\gamma V_{14}+-1+\gamma V_{04}+0+\gamma V_{13}+0 $$
$$4V_{20}=\gamma V_{30}+0+\gamma V_{21}+0+\gamma V_{10}+0+\gamma V_{20}+-1 $$
$$4V_{21}=\gamma V_{31}+0+\gamma V_{22}+0+\gamma V_{11}+0+\gamma V_{20}+0 $$
$$4V_{22}=\gamma V_{32}+0+\gamma V_{23}+0+\gamma V_{12}+0+\gamma V

$$ 4V_{00}=\gamma V_{10}+0+\gamma V_{01}+0+\gamma V_{00}+-1+\gamma V_{00}+-1 $$
$$ 4V_{01}=\gamma V_{11}+0+\gamma V_{02}+0+\gamma V_{01}+-1+\gamma V_{00}+0 $$
$$ 4V_{02}=\gamma V_{12}+0+\gamma V_{03}+0+\gamma V_{02}+-1+\gamma V_{01}+0 $$
$$ 4V_{03}=\gamma V_{13}+0+\gamma V_{04}+0+\gamma V_{03}+-1+\gamma V_{02}+0 $$
$$ 4V_{04}=\gamma V_{14}+0+\gamma V_{04}+-1+\gamma V_{04}+-1+\gamma V_{03}+0 $$
$$ 4V_{10}=\gamma V_{20}+0+\gamma V_{11}+0+\gamma V_{00}+0+\gamma V_{10}+-1 $$
$$ 4V_{11}=\gamma V_{21}+0+\gamma V_{12}+0+\gamma V_{01}+0+\gamma V_{10}+0 $$
$$ 4V_{12}=\gamma V_{22}+0+\gamma V_{13}+0+\gamma V_{02}+0+\gamma V_{11}+0 $$
$$ 4V_{13}=\gamma V_{23}+0+\gamma V_{14}+0+\gamma V_{03}+0+\gamma V_{12}+0 $$
$$ 4V_{14}=\gamma V_{24}+0+\gamma V_{14}+-1+\gamma V_{04}+0+\gamma V_{13}+0 $$
$$ 4V_{20}=\gamma V_{30}+0+\gamma V_{21}+0+\gamma V_{10}+0+\gamma V_{20}+-1 $$
$$ 4V_{21}=\gamma V_{31}+0+\gamma V_{22}+0+\gamma V_{11}+0+\gamma V_{20}+0 $$
$$ 4V_{22}=\gamma V_{32}+0+\gamma V_{23}+0+\gamma V_{12}+0+\gamma V_{21}+0 $$
$$ 4V_{23}=\gamma V_{33}+0+\gamma V_{24}+0+\gamma V_{13}+0+\gamma V_{22}+0 $$
$$ 4V_{24}=\gamma V_{34}+0+\gamma V_{24}+-1+\gamma V_{14}+0+\gamma V_{23}+0 $$
$$ 4V_{30}=\gamma V_{40}+0+\gamma V_{31}+0+\gamma V_{20}+0+\gamma V_{30}+-1 $$
$$ 4V_{31}=\gamma V_{41}+0+\gamma V_{32}+0+\gamma V_{21}+0+\gamma V_{30}+0 $$
$$ 4V_{32}=\gamma V_{42}+0+\gamma V_{33}+0+\gamma V_{22}+0+\gamma V_{31}+0 $$
$$ 4V_{33}=\gamma V_{43}+0+\gamma V_{34}+0+\gamma V_{23}+0+\gamma V_{32}+0 $$
$$ 4V_{34}=\gamma V_{44}+0+\gamma V_{34}+-1+\gamma V_{24}+0+\gamma V_{33}+0 $$
$$ 4V_{40}=\gamma V_{40}+-1+\gamma V_{41}+0+\gamma V_{30}+0+\gamma V_{40}+-1 $$
$$ 4V_{41}=\gamma V_{41}+-1+\gamma V_{42}+0+\gamma V_{31}+0+\gamma V_{40}+0 $$
$$ 4V_{42}=\gamma V_{42}+-1+\gamma V_{43}+0+\gamma V_{32}+0+\gamma V_{41}+0 $$
$$ 4V_{43}=\gamma V_{43}+-1+\gamma V_{44}+0+\gamma V_{33}+0+\gamma V_{42}+0 $$
$$ 4V_{44}=\gamma V_{44}+-1+\gamma V_{44}+-1+\gamma V_{34}+0+\gamma V_{43}+0 $$


Since we did not take the teleport into consideration, now we just need to replace V(1,0) and V(3,0) with the following two cells:

$$ V(s=[1,0]) = 
10 + \gamma V(s=[1,4]) $$

$$ V(s=[3,0]) = 
10 + \gamma V(s=[3,3]) $$

### 4. Solve the linear system


Solve the system of equations $3 * x_0 + x_1 = 9$ and $x_0 + 2 * x_1 = 8$:

In [99]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x

array([ 2.,  3.])

To solve the the linear system that we printed out, we need to transform the problem in a way where all the unknowns are on the left and all the scalars are on the right. Frankly speaking, printing out a problem into a human friendly is only helpful from the perspective of validating if the logic is right, however, if the goal is to solve the problem, I probably will not even bother to do all those hard coding and string manipulation, instead will directly frame the problem in a way that of the linear system format above. However, it is never too late, I am going to maybe copy and paste most of the code above, but modify that in a way that is easier to feed to numpy. 

First we need to know that we have to iterate through each cell. From each iteration, we are supposed to get a list of length 25 that store the coefficients of all the state value function that exist in that equation, if not, use 0. We will also return a number that is the scalar on the right hand side and this number will be used to append to a list $y$ one equation after the other until all finished which will ended up with a length of 25. 

In [154]:
coef = np.ndarray([size*size,size*size])
gamma = 0.9
res = [0 for i in range(size*size)]
for x in range(size):
    for y in range(size):
        
        equation_num = x*size+y
        res[equation_num] = 0
        # skip teleport points for now, deal with later 
        if equation_num in (5, 15):
            continue
        
        
        # top-left:0, bot-left:4, top-right:20, bot-right:24
        cell_num = x*size+y 
        coef[equation_num][cell_num] = 4  
        
        # E: x+1, y
        r = 0
        x_ = x+1
        y_ = y 
        if x_ > size - 1:
            x_ = x
            r = -1 
        coef[equation_num][x_*size+y_] -= gamma 
        res[equation_num] += r
        
        # S: x, y+1
        r = 0
        x_ = x
        y_ = y+1 
        if y_ > size - 1:
            y_ = y
            r = -1
        coef[equation_num][x_*size+y_] -= gamma 
        res[equation_num] += r


        # W: x-1, y
        r = 0
        x_ = x-1
        y_ = y 
        if x_ < 0:
            x_ = x
            r = -1
        coef[equation_num][x_*size+y_] -= gamma 
        res[equation_num] += r
        # N: x, y-1
        r = 0
        x_ = x
        y_ = y-1 
        if y_ < 0:
            y_ = y
            r = -1
        coef[equation_num][x_*size+y_] -= gamma 
        res[equation_num] += r
        
        print('>>> ', x, y)
        print(coef[equation_num])
        print(res)

>>>  0 0
[ 2.2 -0.9  0.   0.   0.  -0.9  0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
[-2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
>>>  0 1
[-0.9  3.1 -0.9  0.   0.   0.  -0.9  0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
[-2, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
>>>  0 2
[ 0.  -0.9  3.1 -0.9  0.   0.   0.  -0.9  0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
[-2, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
>>>  0 3
[ 0.   0.  -0.9  3.1 -0.9  0.   0.   0.  -0.9  0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
[-2, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
>>>  0 4
[  5.729e-313   3.390e+304   2.244e-314  -9.000e-001   2.200e+000
   7.427e-313   1.698e-313   6.942e-310   2.122e-314  -9.000e-001
 

$$ V(s=[1,0]) = 
10 + \gamma V(s=[1,4]) $$

$$ V(s=[3,0]) = 
10 + \gamma V(s=[3,3]) $$

In [192]:
# V(s=[1,0])
equation_num = 1 * size + 0 
coef[equation_num][1 * size + 0] = 1
coef[equation_num][1 * size + 4] -= gamma
res[equation_num] = 10

# V(s=[3,0])
equation_num = 3 * size + 0 
coef[equation_num][3 * size + 0] = 1 
coef[equation_num][3 * size + 3] -= gamma 
res[equation_num] = 10

t = np.array(res)
t.shape = (5,5)
print(t.transpose())

[[-2 10 -1 10 -2]
 [-1  0  0  0 -1]
 [-1  0  0  0 -1]
 [-1  0  0  0 -1]
 [-2 -1 -1 -1 -2]]


Before we even try to pass that to a solver, let's first do a few manual check, how about compare the coefficient with the three states that we have calculated and see if those three equations holds true:

#### S[0,0]
$$(4 - 2 * 0.9)V([0,0]) = 0.9 V([1,0]) + 0.9 V([0,1]) - 2  $$


$$c0 = 2.2$$
$$c5 = -0.9$$
$$c1 = -0.9$$
$$y0 = -2$$

In [156]:
np.set_printoptions(precision=3, suppress=True)
print(coef[0])
print(res[0])

[ 2.2 -0.9  0.   0.   0.  -0.9  0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
-2


#### S[1,0]

$$ V(s=[1,0]) = 10 + 0.9 V(s=[1,4]) $$
$$c5 = 1$$
$$c9 = -0.9$$
$$y5 = 10$$

In [167]:
np.set_printoptions(precision=3, suppress=True)
print(coef[5])
print(res[5])

[ 0.   0.   0.   0.   0.   1.   0.   0.   0.  -0.9  0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
10


#### S[3,2]

$$ 4V([3,2]) = 
0.9 V([4,2]) + 
0.9 V([3,3]) + 
0.9 V([2,2]) + 
0.9 V([3,1]) $$

$$c17=4$$
$$c22=-0.9$$
$$c18=-0.9$$
$$c12=-0.9$$
$$c16=-0.9$$
$$y17=0$$

In [201]:
np.set_printoptions(precision=3, suppress=True)
print(coef[17])
print(res[17])

[ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  -0.9  0.   0.
  0.  -0.9  4.  -0.9  0.   0.   0.  -0.9  0.   0. ]
0


In [206]:
# a = np.array(coef)
# b = np.array(res)
v = np.linalg.solve(coef, res)

print(np.dot(coef[0],v))
print(res[0])

print(np.dot(coef[5],v))
print(res[5])

print(np.dot(coef[17],v))
print(res[17])

-2.0
-2
10.0
10
-9.99200722163e-16
0


In [207]:
v_book = [
    3.3, 1.5, 0.1, -1.0, -1.9,
    8.8, 3.0, 0.7, -0.4, -1.3,
    4.4, 2.3, 0.7, -0.4, -1.2, 
    5.3, 1.9, 0.4, -0.6, -1.4,
    1.5, 0.5, -0.4, -1.2, -2.0
]

print(np.dot(coef[0],v_book))
print(res[0])

print(np.dot(coef[5],v_book))
print(res[5])

print(np.dot(coef[17],v_book))
print(res[17])

-2.01
-2
13.48
10
0.16
0


In [208]:
print(v)

[ 0.642  0.    -0.77  -1.536 -2.545  3.792  1.239 -0.007 -0.863 -1.724
  3.544  1.722  0.363 -0.569 -1.42   7.803  2.508  0.469 -0.61  -1.486
  2.755  1.154 -0.178 -1.126 -1.978]


In [209]:
np.allclose(np.dot(coef, v), res, rtol=0.1)

True

In [211]:
np.allclose(v, v_book, rtol=0.5)

False